{% set name = "python-troveclient" %}
{% set version = "8.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e5826ff3ad4cad1aba66b1544667c858229faa343c98770a4851e0149359017b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - trove = troveclient.shell:main

requirements:
  host:
    - pbr >=2.0.0
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - keystoneauth1 >=3.4.0
    - osc-lib >=1.8.0
    - oslo.i18n >=3.15.3
    - oslo.utils >=3.33.0
    - pbr !=2.1.0,>=2.0.0
    - prettytable >=0.7.2
    - python >={{ python_min }}
    - python-mistralclient !=3.2.0,>=3.1.0
    - python-openstackclient >=3.12.0
    - python-swiftclient >=3.2.0
    - requests >=2.14.2
    - simplejson >=3.5.1

test:
  imports:
    - troveclient
  commands:
    - pip check
    - trove -h
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://docs.openstack.org/python-troveclient/latest
  summary: Client library for OpenStack DBaaS API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tschoonj
